apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: book-db
  template:
    metadata:
      labels:
        service: book-db
    spec:
      containers:
        - name: book-db
          image: postgres:13
          env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_DB
            value: maximalibri_book_db
          - name: POSTGRES_PASSWORD
            value: password

