apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: book
spec:
  selector:
    matchLabels:
      app: book
  replicas: 2
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - image: docker.io/alexandramurgoci/maximalibri-book:1.0
          imagePullPolicy: Always
          name: book
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
