apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: book-description
spec:
  selector:
    matchLabels:
      app: book-description
  replicas: 1
  template:
    metadata:
      labels:
        app: book-description
    spec:
      containers:
        - image: docker.io/alexandramurgoci/maximalibri-book-description:1.0
          imagePullPolicy: Always
          name: book-description
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
