apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: book-rating
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: book-rating
